services:
  mysql_dev:
    container_name: mysql-alex
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - dev_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      

  phpmyadmin_dev:
    container_name: phpmyadmin-alex
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql_dev
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - mysql_dev
    networks:
      - dev_network

  xampp_dev:
    image: tomsik68/xampp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/brechot/einstein/api:/www
    networks:
      - dev_network

  springapp:
    build:
     context: ./ProjetoEcommerce
     dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_dev:3306/ecommerce_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - mysql_dev
    networks:
      - dev_network
 
  django_app:
    build: ./djangoEcommerce
    ports:
      - "8000:8000"
    volumes:
      - ./djangoEcommerce:/usr/src/app
    environment:
      DJANGO_SETTINGS_MODULE: src.settings
      API_URL: http://springapp:8080
    depends_on:
      - springapp
    networks:
      - dev_network
      
  laravelapp:
    build:
     context: ./laravelEcommerce
    ports:
      - "8001:8001"
    volumes:
      - ./laravelEcommerce:/appLaravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_dev
      DB_PORT: 3306
      DB_DATABASE: ecommerce_db
      DB_USERNAME: root
      DB_PASSWORD: root123
    depends_on: 
      mysql_dev:
        condition: service_healthy
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
